version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 30
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.4
